### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wenshan** [Turistforeningen/node-im-resize#18]
Code example error, please follow up.

```
  var image = {
        path: '/Users/hou/work/images-upload-data/test-img/bfk2.jpg',
        width: 500,
        height: 500
    };

    var output = {
        versions: [{
            suffix: '-thumb',
            maxHeight: 150,
            maxWidth: 150,
            aspect: "3:2"
        },{
            suffix: '-square',
            maxWidth: 200,
            aspect: "1:1"
        }]
    };

    resize(image, output, function(error, versions) {
        if (error) { console.error(error); }
        console.log(versions);   // /path/to/image-thumb.jpg
        //console.log(versions[0].width);  // 150
        //console.log(versions[0].height); // 100

        //console.log(versions[1].path);   // /path/to/image-square.jpg
        //console.log(versions[1].width);  // 200
        //console.log(versions[1].height); // 200
    });
```

results:

```

{ Error: Command failed: convert /Users/hou/work/images-upload-data/test-img/bfk2.jpg -auto-orient -strip -write mpr:/Users/hou/work/images-upload-data/test-img/bfk2.jpg +delete mpr:/Users/hou/work/images-upload-data/test-img/bfk2.jpg -quality 80 -crop "500x334+0+83" -resize "150x150" -write /Users/hou/work/images-upload-data/test-img/bfk2-thumb.jpg +delete mpr:/Users/hou/work/images-upload-data/test-img/bfk2.jpg -quality 80 -resize "200" /Users/hou/work/images-upload-data/test-img/bfk2-square.jpg
/bin/sh: convert: command not found

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:568:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: 'convert /Users/hou/work/images-upload-data/test-img/bfk2.jpg -auto-orient -strip -write mpr:/Users/hou/work/images-upload-data/test-img/bfk2.jpg +delete mpr:/Users/hou/work/images-upload-data/test-img/bfk2.jpg -quality 80 -crop "500x334+0+83" -resize "150x150" -write /Users/hou/work/images-upload-data/test-img/bfk2-thumb.jpg +delete mpr:/Users/hou/work/images-upload-data/test-img/bfk2.jpg -quality 80 -resize "200" /Users/hou/work/images-upload-data/test-img/bfk2-square.jpg' }
undefined

```

**Comment by anthonyringoet** [comment]
Can you confirm you have imagemagick installed on your machine? If not, please install it and try again.
